services:
  - type: web
    name: flask-render-demo
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PORT
        value: "10000"
